DROP TABLE IF EXISTS CurrencyQuotes;
CREATE TABLE IF NOT EXISTS CurrencyQuotes (timestamp INTEGER PRIMARY KEY, usdToEur REAL);
DROP TABLE IF EXISTS StonkQuotes;
CREATE TABLE IF NOT EXISTS StonkQuotes (timestamp INTEGER PRIMARY KEY, sp500 REAL);